# 运行环境

FROM jdk8
MAINTAINER wolfe
#持久化到指定目录
VOLUME /tmp
# 将工程jar包（eureka-server-1.0.0.jar）拷贝到 api.jar中
#ENV EUREKA_IP 192.168.162.128
ENV KAFKA_CLUSTER 127.0.0.1:9092
ENV RECOGNITION_IP 172.18.199.141
ENV RECOGNITION_PORT 10102
ENV MYSQL_IP 172.18.199.141
ENV MYSQL_PORT 3306
ENV INSTANCE_IP_ADDRESS 172.18.199.141
ENV DEFAULTZONE http://admin:admin@127.0.0.1:9011/eureka
#ADD  ciip-platform-exec.jar /api.jar
WORKDIR ../../../../target/
ADD  ciip-platform-exec.jar /api.jar
#ADD  *.jar /api.jar
# 执行jar包  "-Djava.security.egd=file:/dev/./urandom"加快随机数产生过程
ENTRYPOINT ["java","-Duser.timezone=GMT+8","-Djava.security.egd=file:/dev/./urandom","-Dglobal.config.path=/Intelligent/config/conf.properties","-jar","/api.jar"]


