spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 100MB #最大请求文件的大小
      max-file-size: 20MB #设置单个文件最大长度
      file-size-threshold: 20MB #当文件达到多少时进行磁盘写入
# 服务端口
server:
  port: 8091
  servlet:
    context-path: /rbac
  tomcat:
    max-http-post-size: -1 #请求传入参数大小限制
    basedir: /aidata/aicareer/applications/aicareer/tmp