aicareer:
  aimokr:
    mysql:
     url: localhost:3306
     username: aicareer
     password: aicareer
#  password: ENC(ZDmMiOphZxP1u04rRdQ5WUR+FXDOndWR)
# 连接四大参数 serverTimezone=UTC会比中国早8个小时
master:
  datasource:
    username: ${aicareer.aimokr.mysql.username}
    password: ${aicareer.aimokr.mysql.password}
    url: jdbc:mysql://${aicareer.aimokr.mysql.url}/aicareer?serverTimezone=UTC&useUnicode=true&useSSL=false&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
rbac:
  datasource:
    username: ${aicareer.aimokr.mysql.username}
    password: ${aicareer.aimokr.mysql.password}
    url: jdbc:mysql://${aicareer.aimokr.mysql.url}/aicareer?serverTimezone=UTC&useUnicode=true&useSSL=false&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver

#密码加密传输，前端公钥加密，后端私钥解密
rsa:
  private_key: MIIBUwIBADANBgkqhkiG9w0BAQEFAASCAT0wggE5AgEAAkEA0vfvyTdGJkdbHkB8mp0f3FE0GYP3AYPaJF7jUd1M0XxFSE2ceK3k2kw20YvQ09NJKk+OMjWQl9WitG9pB6tSCQIDAQABAkA2SimBrWC2/wvauBuYqjCFwLvYiRYqZKThUS3MZlebXJiLB+Ue/gUifAAKIg1avttUZsHBHrop4qfJCwAI0+YRAiEA+W3NK/RaXtnRqmoUUkb59zsZUBLpvZgQPfj1MhyHDz0CIQDYhsAhPJ3mgS64NbUZmGWuuNKp5coY2GIj/zYDMJp6vQIgUueLFXv/eZ1ekgz2Oi67MNCk5jeTF2BurZqNLR3MSmUCIFT3Q6uHMtsB9Eha4u7hS31tj1UWE+D+ADzp59MGnoftAiBeHT7gDMuqeJHPL4b+kC+gzV4FGTfhR9q3tTbklZkD2A==

#jwt
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间 此处单位/毫秒 ，默认4小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 14400000
  # 在线用户key
  online-key: online-token-
  # 验证码
  code-key: code-key-
  # token 续期检查时间范围（默认30分钟，单位毫秒），在token即将过期的一段时间内用户操作了，则给用户的token续期
  detect: 1800000
  # 续期时间范围，默认1小时，单位毫秒
  renew: 3600000